name: Tai Tong's Blog
description: Blog about everything from coding to anything I find interesting.
meta_description: "Tai Rui Tong's blog about everything"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://tairuitong.me'
google_analytics: 'UA-54598212-1'
disqus_shortname: 'theperfectsquareca'
timezone: America/New_York
# Details for the RSS feed generator
url:            'http://tairuitong.me'
author:         'Tai Tong'
authorTwitter:  'TaiRTong'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
            author: "Tai Tong"